// <auto-generated />
namespace MovieStarEFUygulama.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class türadigerekliliğnikaldırdım : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(türadigerekliliğnikaldırdım));
        
        string IMigrationMetadata.Id
        {
            get { return "202202130844518_tür adi gerekliliğni kaldırdım"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
